# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ratouney/baurens/ratlibpp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ratouney/baurens/ratlibpp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ratouney/baurens/ratlibpp/CMakeFiles /home/ratouney/baurens/ratlibpp/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ratouney/baurens/ratlibpp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Rat

# Build rule for target.
Rat: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Rat
.PHONY : Rat

# fast build rule for target.
Rat/fast:
	$(MAKE) -f CMakeFiles/Rat.dir/build.make CMakeFiles/Rat.dir/build
.PHONY : Rat/fast

#=============================================================================
# Target rules for targets named tester

# Build rule for target.
tester: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tester
.PHONY : tester

# fast build rule for target.
tester/fast:
	$(MAKE) -f CMakeFiles/tester.dir/build.make CMakeFiles/tester.dir/build
.PHONY : tester/fast

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/tester.dir/build.make CMakeFiles/tester.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/tester.dir/build.make CMakeFiles/tester.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/tester.dir/build.make CMakeFiles/tester.dir/main.cpp.s
.PHONY : main.cpp.s

src/Error.o: src/Error.cpp.o

.PHONY : src/Error.o

# target to build an object file
src/Error.cpp.o:
	$(MAKE) -f CMakeFiles/Rat.dir/build.make CMakeFiles/Rat.dir/src/Error.cpp.o
.PHONY : src/Error.cpp.o

src/Error.i: src/Error.cpp.i

.PHONY : src/Error.i

# target to preprocess a source file
src/Error.cpp.i:
	$(MAKE) -f CMakeFiles/Rat.dir/build.make CMakeFiles/Rat.dir/src/Error.cpp.i
.PHONY : src/Error.cpp.i

src/Error.s: src/Error.cpp.s

.PHONY : src/Error.s

# target to generate assembly for a file
src/Error.cpp.s:
	$(MAKE) -f CMakeFiles/Rat.dir/build.make CMakeFiles/Rat.dir/src/Error.cpp.s
.PHONY : src/Error.cpp.s

src/File.o: src/File.cpp.o

.PHONY : src/File.o

# target to build an object file
src/File.cpp.o:
	$(MAKE) -f CMakeFiles/Rat.dir/build.make CMakeFiles/Rat.dir/src/File.cpp.o
.PHONY : src/File.cpp.o

src/File.i: src/File.cpp.i

.PHONY : src/File.i

# target to preprocess a source file
src/File.cpp.i:
	$(MAKE) -f CMakeFiles/Rat.dir/build.make CMakeFiles/Rat.dir/src/File.cpp.i
.PHONY : src/File.cpp.i

src/File.s: src/File.cpp.s

.PHONY : src/File.s

# target to generate assembly for a file
src/File.cpp.s:
	$(MAKE) -f CMakeFiles/Rat.dir/build.make CMakeFiles/Rat.dir/src/File.cpp.s
.PHONY : src/File.cpp.s

src/Regex.o: src/Regex.cpp.o

.PHONY : src/Regex.o

# target to build an object file
src/Regex.cpp.o:
	$(MAKE) -f CMakeFiles/Rat.dir/build.make CMakeFiles/Rat.dir/src/Regex.cpp.o
.PHONY : src/Regex.cpp.o

src/Regex.i: src/Regex.cpp.i

.PHONY : src/Regex.i

# target to preprocess a source file
src/Regex.cpp.i:
	$(MAKE) -f CMakeFiles/Rat.dir/build.make CMakeFiles/Rat.dir/src/Regex.cpp.i
.PHONY : src/Regex.cpp.i

src/Regex.s: src/Regex.cpp.s

.PHONY : src/Regex.s

# target to generate assembly for a file
src/Regex.cpp.s:
	$(MAKE) -f CMakeFiles/Rat.dir/build.make CMakeFiles/Rat.dir/src/Regex.cpp.s
.PHONY : src/Regex.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Rat"
	@echo "... tester"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/Error.o"
	@echo "... src/Error.i"
	@echo "... src/Error.s"
	@echo "... src/File.o"
	@echo "... src/File.i"
	@echo "... src/File.s"
	@echo "... src/Regex.o"
	@echo "... src/Regex.i"
	@echo "... src/Regex.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

